#!/bin/bash



#####################################
#~~~~~~~~~~~~~Help Command~~~~~~~~~~#
#####################################
Help()
{
        #Displays the help information

	echo "~~~~~~~~~~~~~~~~~~~"
        echo "Bash script for when I blow out my OS! You know... again."
	echo "Installs a bunch of useful utilities, makes a few aliases."
	echo "~~~~~~~~~~~~~~~~~~~"
	echo "Run chmod +x on this file to make it executable"
	echo "Run the script!"
	echo "Some of the installs require sudo, so it will prompt you for credentials!"
	echo "~~~~~~~~~~~~~~~~~~~"
	echo "-h ~ shows this command"
	echo "-v ~ shows the version"
	echo "-a ~ shows the author info"
}

#####################################
#~~~~~~~~~~~~Version Command~~~~~~~~#
#####################################
Version()
{
        echo "Version 1.0"
}

#####################################
#~~~~~~~~~~~~Author Command~~~~~~~~~#
#####################################
Author()
{
	echo "~~~~~~Author~~~~~~"
	echo "Dennis Capone (DDMAC)"
        echo "https://github.com/dcap0"
	echo "~~~~~~~~~~~~~~~~~~~"

	echo "Feel free to fork and edit this!"
}



while getopts ":hav" option;
do
	case "$option" in
		\?)
			echo "Invalid Option"
			exit;;
		h)
			Help
			exit;;
		a)
			Author
			exit;;
		v)
			Version
			exit;
	esac
done


#####################################
#~~~~~~~~~~~~~Main Body~~~~~~~~~~~~~#
#####################################

echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Beginning Execution'
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'

cd

echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Installing utilities'
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'

sudo apt update
sudo apt install snapd git vim openjdk-11-jdk  openjdk-8-jdk torbrowser-launcher curl python3-pip htop trash-cli net-tools mlocate software-properties-common apt-transport-https wget terminator websocat rkhunter

sudo pip3 install thefuck


echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Installing spotify'
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
sudo snap install --classic spotify

echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Installing VSCode'
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
sudo snap install code


echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Creating user bin directory and Installing Intellij IDE'
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
mkdir ./bin && cd ./bin
wget https://download.jetbrains.com/idea/ideaIU-2021.1.3.tar.gz && tar -xvf ./ideaIU-2021.1.3.tar.gz

cd

echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Adding useful aliases to .bashrc (Also adding a sfw command for one of the utilities)'
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'

echo 'alias update="sudo apt update && sudo apt full-upgrade -y"' >> ~/.bashrc
echo 'alias jcv="sudo update-alternatives --config javac' >> ~/.bashrc
echo 'alias jdkv="sudo update-alternatives --config java' >> ~/.bashrc
echo 'eval $(thefuck --alias)' >> ~/.bashrc
echo 'eval $(thefuck --alias plz)' >> ~/.bashrc

echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Starting ssh key generation'
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
ssh-keygen

echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Applying new aliases'
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'

source ~/.bashrc

echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'Script Execution Complete! Have fun!'
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'

 
