#!/bin/bash

cd

sudo apt update
sudo apt install snapd git vim openjdk-11-jdk  openjdk-8-jdk torbrowser-launcher curl python3-pip htop trash-cli net-tools mlocate software-properties-common apt-transport-https wget terminator websocat rkhunter

sudo pip3 install thefuck

sudo snap install --classic spotify

mkdir ./bin && cd ./bin
wget https://download.jetbrains.com/idea/ideaIU-2021.1.3.tar.gz
tar -xvf ./ideaIU-2021.1.3.tar.gz

wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add - && sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

sudo apt update
sudo apt install code

cd

echo 'alias update="sudo apt update && sudo apt full-upgrade -y"' >> ~/.bashrc
echo 'alias jcv="sudo update-alternatives --config javac' >> ~/.bashrc
echo 'alias jdkv="sudo update-alternatives --config java' >> ~/.bashrc
echo 'eval $(thefuck --alias)' >> ~/.bashrc
echo 'eval $(thefuck --alias plz)' >> ~/.bashrc

ssh-keygen

source ~/.bashrc
 
